### ISSUE TITLE
Credentials

### ISSUE THREAD

**Issue by ejramalho** [bitbull-team/aws-rds-autoscaling#1]
Could you please share a real example on how to configure credentials file?

**Comment by daaru00** [comment]
Hi @ejramalho 

the `credentials` file is really easy to create, make a copy of [credentials.sample](https://github.com/bitbull-team/aws-rds-autoscaling/blob/master/credentials.sample) renaming into `credentials`.
Then set your profile name configured in AWS CLI, for example:
```
export AWS_PROFILE = myproject
```


If you need help to configure your AWS CLI and create a new profile please refer to 
[AWS guide](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html)

You can create a new profile configuration using:
```
aws configure --profile myproject
```
and follow the instructions
